/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'vingupta3' at '4/11/19 5:53 PM' with Gradle 2.6
 *
 * @author vingupta3, @date 4/11/19 5:53 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
